//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPPKBrunoHrgovicMVC
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Actor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Actor()
        {
            this.Movie = new HashSet<Movie>();
            this.ActorUploadedFiles = new HashSet<ActorUploadedFiles>();
        }
    
        public int IDActor { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        [Range(1,Int32.MaxValue, ErrorMessage ="Vrijednost mora biti jednaka ili veca od 1")]
        public int Age { get; set; }
        [Required]
        public string Gender { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movie> Movie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActorUploadedFiles> ActorUploadedFiles { get; set; }
    }
}
