//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPPKBrunoHrgovicMVC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        internal readonly object Actors;

        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actor> ActorSet { get; set; }
        public virtual DbSet<Director> DirectorSet { get; set; }
        public virtual DbSet<Movie> MovieSet { get; set; }
        public virtual DbSet<ActorUploadedFiles> ActorUploadedFilesSet { get; set; }
        public virtual DbSet<DirectorUploadedFiles> DirectorUploadedFilesSet { get; set; }
        public virtual DbSet<MovieUploadedFiles> MovieUploadedFilesSet { get; set; }
    }
}
