//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPPKBrunoHrgovicMVC
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Movie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movie()
        {
            this.MovieUploadedFiles = new HashSet<MovieUploadedFiles>();
        }
    
        public int IDMovie { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        [Range(1, Int32.MaxValue, ErrorMessage = "Vrijednost mora biti jednaka ili veca od 1")]
        public string Duration { get; set; }
        [Required]
        [Range(1, Int32.MaxValue, ErrorMessage = "Vrijednost mora biti jednaka ili veca od 1")]
        public int Release { get; set; }
        public int ActorIDActor { get; set; }
        public int DirectorIDDirector { get; set; }
        [Required (ErrorMessage = "Potrebno je dodati glumca")]
        public virtual Actor Actor { get; set; }
        [Required(ErrorMessage = "Potrebno je dodati direktora")]
        public virtual Director Director { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieUploadedFiles> MovieUploadedFiles { get; set; }
    }
}
